routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('welcome/', function() {
    return view('welcome');
});

Route::get('catalog/', function() {
    return view('menu');
});

Route::get('catalog/medicines', function() {
    return view('product', ['name' => 'medic']);
});

Route::get('catalog/med_equip', function() {
    return view('product', ['name' => 'medic_equip']);
});

Route::get('/medicines/panadol', function () {
    return view('detail', ['id' => 'medic1']);
});

Route::get('/medicines/ultraflu', function () {
    return view('detail', ['id' => 'medic2']);
});

Route::get('/medicines/vitacimin', function () {
    return view('detail', ['id' => 'medic3']);
});

Route::get('/med_equip/stetoskop', function () {
    return view('detail', ['id' => 'med_equip1']);
});

Route::get('/med_equip/masker', function () {
    return view('detail', ['id' => 'med_equip2']);
});

/////////////////////////////////////////////////

Route::get('/helloworld', function (){
    return 'Hello World, Pak Dosen';
});

Route::view('/selamatdatang','welcome');

Route::get('user/{id}', function($id) {
    return 'User '.$id;
});

Route::get('posts/{post}/comments/{comment}', function($postId, $commentId) {
    return 'Post : ' .$postId.'<br>comments : '.$commentId;
});

Route::get('user/{name?}', function($name = 'John') {
    return $name;
});

Route::get('user/profile', function() {
    //
})->name('profile');

Route::get('user/{id}/profile', function($id) {
    //
})->name('profile');

Route::get('wfp/{kelas}', function($kelas){
    if ($kelas == "C" || $kelas == "c") {
        return 'WFP Kelas '.$kelas;
    }
    else {
        return "Bukan Kelas Saya";
    }
});

Route::get('greeting', function() {
    return view('welcome', ['name' => 'Bagus']);
});

Route::get('/', function() {
    return view('welcome');
});

// Week 8
Auth::routes();
Route::get('/', 'MedicineController@front_index');

Route::middleware(['auth'])->group(function() {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('supplier', 'SupplierController');
    Route::resource('obat', 'MedicineController');
    Route::resource('transaksi', 'TransactionController');
    Route::resource('kategori_obat', 'CategoryController');

    Route::post('/supplier/getEditForm', 'SupplierController@getEditForm')->name('supplier.getEditForm');
    Route::post('/supplier/getEditForm2', 'SupplierController@getEditForm2')->name('supplier.getEditForm2');
    Route::post('/supplier/saveData', 'SupplierController@saveData')->name('supplier.saveData');
    Route::post('/supplier/deleteData', 'SupplierController@deleteData')->name('supplier.deleteData');
    Route::post('/supplier/saveDataField', 'SupplierController@saveDataField')->name('supplier.saveDataField');
    Route::post('/supplier/changeLogo', 'SupplierController@changeLogo')->name('supplier.changeLogo');

    Route::get('obatsatukategori', 'MedicineController@tugas')->name('medicines.tugas');
    Route::post('/obat/showInfo','MedicineController@showInfo')->name('obat.showInfo');
    Route::get('cart', 'MedicineController@cart');
    Route::get('add-to-cart/{id}', 'MedicineController@addToCart');
    Route::post('/obat/saveDataFieldMedicine', 'MedicineController@saveDataFieldMedicine')->name('obat.saveDataFieldMedicine');
    Route::post('/obat/changeImageMedicine', 'MedicineController@changeImageMedicine')->name('obat.changeImageMedicine');

    Route::get('transaction', 'TransactionController@Transaction')->name('transaction.transactionlist');
    Route::post('transaction/showDataAjax','TransactionController@showAjax')->name('transaction.showAjax');
    Route::get('/submit_checkout', 'TransactionController@submit_front')->name('submitcheckout');
    Route::get('/checkout', 'TransactionController@form_submit_front');
    Route::get('/cetakpemesanan/{id}', 'TransactionController@print_detail')->name('cetakpesan');

    Route::get('/report/listmedicine/{id}','CategoryController@showlist')->name('reportShowMedicine');
});

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Transaction;
use App\Buyer;
use App\User;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
Use PDF;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
    }

    public function Transaction() 
    {
        $transaction = Transaction::all();

        return view('transaction.transactionlist', compact('transaction'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = Buyer::all();
        $data2 = User::all();

        return view('transaction.create', compact('data', 'data2'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = new Transaction;
        $data->transaction_date = $request->transaction_date;
        $data->buyer_id = $request->buyer_id;
        $data->user_id = $request->user_id;
        $data->save();
        return redirect('transaction')->with('status', 'Transaction is added');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function show($transaction)
    {
        // dd($transaction);
        $transaction = Transaction::find($transaction);
        return view('transaction.show', compact('transaction'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function edit(Transaction $transaction)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Transaction $transaction)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function destroy(Transaction $transaction)
    {
        //
    }

    public function showAjax(Request $request)
    {
        $id = ($request->get('id'));
        $data = Transaction::find($id);
        $medicine = $data->medicines;
        return response()
            ->json(array('msg'=> view('transaction.showAjax', compact('data', 'medicine'))->render()), 200);
    }

    public function form_submit_front()
    {
        $this->authorize('checkmember');
        return view('frontend.checkout');
    }

    public function submit_front()
    {
        $this->authorize('checkmember');

        $cart = session()->get('cart');
        $user = Auth::user();
        $t = new Transaction;
        $t->user_id = $user->id;
        $t->transaction_date = Carbon::now()->toDateTimeString();
        $t->save();

        $totalharga = $t->insertProduct($cart, $user);
        $t->total = $totalharga;
        $t->save();

        session()->forget('cart');
        return redirect('home');
    }

    public function print_detail($id_transaction)
    {
        $transaction = Transaction::find($id_transaction);
        $pdf = PDF::loadview('transaction.detailpdf', ['transaction'=>$transaction]);
        $name = "laporan-pemesanan" .$transaction->id . $transaction->transaction_date. ".pdf";
        return $pdf->download($name);
        
    }
}

resources/views/transaction/create.blade.php
@extends('layouts.conquer2')

@section('title')
    Tambah Transaction
@endsection

@section('content')
<form method="POST" action="{{route('transaksi.store')}}" class="form-horizontal">
    @csrf
    <div class="form-body">
        <h3 align='center'>Tambah Transaksi Baru</h3><br>
        <div class="form-group">
            <label class="col-md-3 control-label">Transaction Date</label>
            <div class="col-md-4">
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="fa fa-user"></i>
                    </span>
                    <input id="transaction_date" name="transaction_date" type="date" class="form-control" placeholder="Transaction Date">
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Buyer</label>
            <div class="col-md-4">
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="fa fa-envelope"></i>
                    </span>
                    <select id="buyer_id" name="buyer_id">
                        @foreach($data as $d)
                            <option value="{{$d->id}}">{{$d->name}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">User</label>
            <div class="col-md-4">
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="fa fa-envelope"></i>
                    </span>
                    <select id="user_id" name="user_id">
                        @foreach($data2 as $d)
                            <option value="{{$d->id}}">{{$d->name}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>
    </div>
    <div class="form-actions">
        <div class="row">
            <div class="col-md-offset-3 col-md-9">
                <button type="submit" class="btn btn-primary">Submit</button>
                <button type="button" class="btn btn-default">Cancel</button>
            </div>
        </div>
    </div>
</form>
@endsection

resources/views/transaction/detailpdf.blade.php
<h1>INVOICE</h1>
<div class="portlet">
    <div class="portlet-title">
        <a href="{{ route('cetakpesan', $transaction->id) }}" class="btn btn-danger">Cetak</a><br>
        <b>Pemesanan dari transaksi kode : {{ $transaction->id }}</b>
        <b>Tanggal Pemesanan : {{ $transaction->transaction_date }}</b>
    </div>

    <div class="portlet-body">
        <div class="row">
            <table id="cart" class="table table-hover table-condensed">
                <thead>
                    <tr>
                        <th style="width:50%">Product</th>
                        <th style="width:10%">Price</th>
                        <th style="width:8%">Quantity</th>
                        <th style="width:22%" class="text-center">Subtotal</th>
                        <th style="width:10%"></th>
                    </tr>
                </thead>
                <tbody>
                    <?php $ts = $transaction->medicines; ?>
                    @foreach($ts as $m)
                    <tr>
                        <td data-th="Product">
                            <div class="row">
                                <!-- <div class="col-sm-3 hidden-xs"><img src="{{ asset ('img/' .$m->image )}}" width="100" height="100" class="img-responsive"/></div> -->
                                <div class="col-sm-9">
                                    <h4 class="nomargin">{{ $m->generic_name }}</h4>
                                </div>
                            </div>
                        </td>
                        <td data-th="Price">Rp. {{ $m->price }}</td>
                        <td data-th="Quantity">{{ $m->pivot->quantity }}</td>
                        <td data-th="Subtotal" class="text-center">Rp. {{ $m->price * $m->pivot->quantity }}</td>
                        <td class="actions" data-th=""></td>
                    </tr>
                    @endforeach
                </tbody>
                <tfoot>
                    <tr class="visible-xs">
                        <td class="text-center"><strong>Total Rp. {{ $transaction->total }}</strong></td>
                    </tr>
                    <tr>
                        <td><a href="{{ url('/home') }}" class="btn btn-warning"><i class="fa fa-angle-left"></i> Kembali ke Daftar Pemesanan</a></td>
                        <td class="hidden-xs"></td>
                        <td class="hidden-xs"></td>
                        <td class="hidden-xs text-center"><strong>Total Rp. {{ $transaction->total }}</strong></td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

resources/views/transaction/show.blade.php
@extends('layouts.frontend')

@section('content')
<div class="portlet">
    <div class="portlet-title">
        <a href="{{ route('cetakpesan', $transaction->id) }}" class="btn btn-danger">Cetak</a><br>
        <b>Pemesanan dari transaksi kode : {{ $transaction->id }}</b>
        <b>Tanggal Pemesanan : {{ $transaction->transaction_date }}</b>
    </div>

    <div class="portlet-body">
        <div class="row">
            <table id="cart" class="table table-hover table-condensed">
                <thead>
                    <tr>
                        <th style="width:50%">Product</th>
                        <th style="width:10%">Price</th>
                        <th style="width:8%">Quantity</th>
                        <th style="width:22%" class="text-center">Subtotal</th>
                        <th style="width:10%"></th>
                    </tr>
                </thead>
                <tbody>
                    <?php $ts = $transaction->medicines ?>
                    @foreach($ts as $m)
                    <tr>
                        <td data-th="Product">
                            <div class="row">
                                <div class="col-sm-3 hidden-xs"><img src="{{ asset ('img/' .$m->image )}}" width="100" height="100" 
                                    class="img-responsive"/></div>
                                <div class="col-sm-9">
                                    <h4 class="nomargin">{{ $m->generic_name }}</h4>
                                </div>
                            </div>
                        </td>
                        <td data-th="Price">Rp. {{ $m->price }}</td>
                        <td data-th="Quantity">{{ $m->pivot->quantity }}</td>
                        <td data-th="Subtotal" class="text-center">Rp. {{ $m->price * $m->pivot->quantity }}</td>
                        <td class="actions" data-th=""></td>
                    </tr>
                    @endforeach
                </tbody>
                <tfoot>
                    <tr class="visible-xs">
                        <td class="text-center"><strong>Total Rp. {{ $transaction->total }}</strong></td>
                    </tr>
                    <tr>
                        <td><a href="{{ url('/home') }}" class="btn btn-warning"><i class="fa fa-angle-left"></i> Kembali ke Daftar Pemesanan</a></td>
                        <td class="hidden-xs"></td>
                        <td class="hidden-xs"></td>
                        <td class="hidden-xs text-center"><strong>Total Rp. {{ $transaction->total }}</strong></td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
@endsection

resources/views/transaction/showAjax.blade.php
<div class='portlet'>
    <div class="portlet-title">
        <b>Tampilan transaksi dari: {{ $data->id }} - {{ $data->transaction_date }}</b>
    </div>
    <div class="portlet-body">
        <div class="row">
            @foreach($medicine as $m)
            <div class="col-md-4">
                <div class="thumbnail">
                <img src="{{ asset ('img/' .$m -> image)}}" style="width:100px; height:100px;">
                    <div class="caption">
                        <p align="center"><b>{{ $m->generic_name }}</b></p>
                        <hr/>
                        <p>Kategori: {{ $m->category->name }}</p>
                        <p>Harga: Rp. {{ $m->price }} ,- </p>
                        <p>Jumlah Beli: {{ $m->pivot->quantity }}</p>
                    </div>
                </div>
            </div>
            @endforeach
        </div>
    </div>
</div>

resources/views/transaction/transactionlist.blade.php
@extends('layouts.conquer2')

@section('title')
  Daftar Transaksi
@endsection

@section('javascript')
<script>
function getDetailData(id)
    {
    $.ajax({
        type:'POST',
        url:'{{route("transaction.showAjax")}}',
        data:'_token=<?php echo csrf_token() ?> &id=' + id,
        success: function(data){
        $("#msg").html(data.msg);
        }
    });
    }
</script>
@endsection

@section('content')
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 align='center'><b>Rincian Pembelian</b></h4>
            </div>
            <div class="modal-body" id="modal-body">
                <div>
                    <div id="msg"></div>
                </div>
            </div>
        </div>
    </div>
</div>

@if (session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
@endif

<div class="page-toolbar">
      <a href="{{ url('transaksi/create') }}" class='btn btn-info' type="button">+ Transaksi baru</a>
</div><br>

<table class='table'>
    <thead>
        <tr>
            <th>ID</th>
            <th>Pembeli</th>
            <th>Tanggal Transaksi</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($transaction as $d)
    <tr>
        <td>{{ $d->id }}</td>
        <td>{{ $d->user->name }}</td>
        <td>{{ $d->created_at }}</td>
        <td>
            <a class="btn btn-default" data-toggle="modal" data-target="#modal" onclick="getDetailData({{$d->id}});">Lihat Rincian Pembelian</a>
        </td>
    </tr>
    @endforeach
    </tbody>
</table>
@endsection