routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('welcome/', function() {
    return view('welcome');
});

Route::get('catalog/', function() {
    return view('menu');
});

Route::get('catalog/medicines', function() {
    return view('product', ['name' => 'medic']);
});

Route::get('catalog/med_equip', function() {
    return view('product', ['name' => 'medic_equip']);
});

Route::get('/medicines/panadol', function () {
    return view('detail', ['id' => 'medic1']);
});

Route::get('/medicines/ultraflu', function () {
    return view('detail', ['id' => 'medic2']);
});

Route::get('/medicines/vitacimin', function () {
    return view('detail', ['id' => 'medic3']);
});

Route::get('/med_equip/stetoskop', function () {
    return view('detail', ['id' => 'med_equip1']);
});

Route::get('/med_equip/masker', function () {
    return view('detail', ['id' => 'med_equip2']);
});

/////////////////////////////////////////////////

Route::get('/helloworld', function (){
    return 'Hello World, Pak Dosen';
});

Route::view('/selamatdatang','welcome');

Route::get('user/{id}', function($id) {
    return 'User '.$id;
});

Route::get('posts/{post}/comments/{comment}', function($postId, $commentId) {
    return 'Post : ' .$postId.'<br>comments : '.$commentId;
});

Route::get('user/{name?}', function($name = 'John') {
    return $name;
});

Route::get('user/profile', function() {
    //
})->name('profile');

Route::get('user/{id}/profile', function($id) {
    //
})->name('profile');

Route::get('wfp/{kelas}', function($kelas){
    if ($kelas == "C" || $kelas == "c") {
        return 'WFP Kelas '.$kelas;
    }
    else {
        return "Bukan Kelas Saya";
    }
});

Route::get('greeting', function() {
    return view('welcome', ['name' => 'Bagus']);
});

Route::get('/', function() {
    return view('welcome');
});

// Week 8
Auth::routes();
Route::get('/', 'MedicineController@front_index');

Route::middleware(['auth'])->group(function() {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('supplier', 'SupplierController');
    Route::resource('obat', 'MedicineController');
    Route::resource('transaksi', 'TransactionController');
    Route::resource('kategori_obat', 'CategoryController');

    Route::post('/supplier/getEditForm', 'SupplierController@getEditForm')->name('supplier.getEditForm');
    Route::post('/supplier/getEditForm2', 'SupplierController@getEditForm2')->name('supplier.getEditForm2');
    Route::post('/supplier/saveData', 'SupplierController@saveData')->name('supplier.saveData');
    Route::post('/supplier/deleteData', 'SupplierController@deleteData')->name('supplier.deleteData');
    Route::post('/supplier/saveDataField', 'SupplierController@saveDataField')->name('supplier.saveDataField');
    Route::post('/supplier/changeLogo', 'SupplierController@changeLogo')->name('supplier.changeLogo');

    Route::get('obatsatukategori', 'MedicineController@tugas')->name('medicines.tugas');
    Route::post('/obat/showInfo','MedicineController@showInfo')->name('obat.showInfo');
    Route::get('cart', 'MedicineController@cart');
    Route::get('add-to-cart/{id}', 'MedicineController@addToCart');
    Route::post('/obat/saveDataFieldMedicine', 'MedicineController@saveDataFieldMedicine')->name('obat.saveDataFieldMedicine');
    Route::post('/obat/changeImageMedicine', 'MedicineController@changeImageMedicine')->name('obat.changeImageMedicine');

    Route::get('transaction', 'TransactionController@Transaction')->name('transaction.transactionlist');
    Route::post('transaction/showDataAjax','TransactionController@showAjax')->name('transaction.showAjax');
    Route::get('/submit_checkout', 'TransactionController@submit_front')->name('submitcheckout');
    Route::get('/checkout', 'TransactionController@form_submit_front');
    Route::get('/cetakpemesanan/{id}', 'TransactionController@print_detail')->name('cetakpesan');

    Route::get('/report/listmedicine/{id}','CategoryController@showlist')->name('reportShowMedicine');
});

app/Medicine.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Medicine extends Model
{
    public function category() {
        return $this->belongsTo('App\Category', 'category_id');
    }
    
    public function transaction() {
        return $this->belongsToMany('App\Transaction', 'medicine_transaction', 'medicine_id', 'transaction_id')
        ->withPivot('quantity', 'price');
    }

    public function supplier() {
        return $this->belongsTo('App\Supplier', 'supplier_id');
    }
}

app/Http/Controllers/MedicineController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Medicine;
use App\Supplier;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class MedicineController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $listdata = DB::select(DB::raw("SELECT * FROM medicines"));
        // $listdata = DB::table('med')->get();
        $listdata = Medicine::all();

        return view('medicine.index', compact('listdata'));
    }

    public function tugas()
    {
        $listdata = DB::table('medicines')
            ->join('categories', 'medicines.category_id', '=', 'categories.id')
            ->where('medicines.category_id', '=', 1)
            ->select('medicines.*', 'categories.name as category_name')
            ->get();

        return view('medicine.obatKategori', compact('listdata'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = Category::all();
        $data2 = Supplier::all();
        $dataMedicine = Medicine::all();

        return view('medicine.create', compact('data', 'data2', 'dataMedicine'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = new Medicine;
        
        $file = $request->file('image');
        $imgFolder = 'img';
        $imgFile = time()."_".$file->getClientOriginalName();
        $file->move($imgFolder, $imgFile);
        $data->image=$imgFile;

        $data->generic_name = $request->generic_name;
        $data->form = $request->form;
        $data->restriction_formula = $request->restriction_formula;
        $data->price = $request->price;
        $data->description = $request->description;
        $data->category_id = $request->category_id;
        $data->supplier_id = $request->supplier_id;
        $data->faskes1 = $request->faskes1;
        $data->faskes2 = $request->faskes2;
        $data->faskes3 = $request->faskes3;
        $data->save();
        return redirect('obat')->with('status', 'Medicine is added');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Medicine  $medicine
     * @return \Illuminate\Http\Response
     */
    public function show($medicine)
    {
        $res = Medicine::find($medicine);
        $msg = "";
        if($res){
            $msg = $res;
        }
        else{
            $msg = null;
        }
        return view('medicine.show', compact('msg'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Medicine  $medicine
     * @return \Illuminate\Http\Response
     */
    public function edit($medicine)
    {
        $data = Medicine::find($medicine);
        $medicinecategory = $data->category;
        $medicinesupplier = $data->supplier;
        $category = Category::all();
        $supplier = Supplier::all();
        return view('medicine.edit', compact('data', 'category', 'supplier'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Medicine  $medicine
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Medicine $medicine, $id)
    {
        $medicine = Medicine::find($id);
        $medicine->generic_name=$request->get('generic_name');
        $medicine->form=$request->get('form');
        $medicine->restriction_formula=$request->get('restriction_formula');
        $medicine->price=$request->get('price');
        $medicine->description=$request->get('description');
        $medicine->category_id=$request->get('category_id');
        $medicine->faskes1=$request->get('faskes1');
        $medicine->faskes2=$request->get('faskes2');
        $medicine->faskes3=$request->get('faskes3');

        $file = $request->file('image');
        $imgFolder = 'img';
        $imgFile = time()."_".$file->getClientOriginalName();
        $file->move($imgFolder, $imgFile);
        $medicine->image = $imgFile;

        $medicine->supplier_id=$request->get('supplier_id');

        $medicine->save();
        return redirect()->route('obat.index')->with('status', 'Medicine data is changed');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Medicine  $medicine
     * @return \Illuminate\Http\Response
     */
    public function destroy($medicine)
    {
        $this->authorize('delete-permission', $medicine);

        try {
            $data = Medicine::find($medicine);
            $data->delete();
            return redirect()->route('obat.index')->with('status', 'Data obat berhasil dihapus');
        } catch (\PDOEXCEPTION $e) {
            $msg = "Data gagal dihapus. Pastikan data child sudah hilang atau tidak berhubungan";

            return redirect()->route('obat.index')->with('error', $msg);
        }
    }

    public function showInfo()
    {
        $result = Medicine::orderBy('price', 'DESC')->first();
        return response()->json(array(
            'status' => 'oke',
            'msg' => "<div class='alert alert-info'>
            Did you know? <br>The most expensive product is " . 
            $result->generic_name . "</div>"
        ), 200);
    }

    public function front_index()
    {
        $medicines = Medicine::all();
        return view('frontend.medicine', compact('medicines'));
    }

    public function addToCart($id)
    {
        $m = Medicine::find($id);
        $cart = session()->get('cart');
        if(!isset($cart[$id]))
        {
            $cart[$id] = [
                "name" => $m->generic_name,
                "quantity" => 1,
                "price" => $m->price,
                "photo" => $m->image
            ];
        }
        else
        {
            $cart[$id]['quantity']++;
        }
        session()->put('cart', $cart);
        return redirect()->back()->with('success', 'Medicine added to cart successfully');
    }

    public function cart()
    {
        return view('frontend.cart');
    }

    public function saveDataFieldMedicine(Request $request)
    {
        $id = $request->get('id');
        $fname = $request->get('fname');
        $value = $request->get('value');

        $Medicine = Medicine::find($id);
        $Medicine->$fname = $value;
        $Medicine->save();
        return response()->json(array(
            'status'=>'ok',
            'msg'=>'Medicine data updated'
        ),200);
    }

    public function changeImageMedicine(Request $request)
    {
        $id = $request->get('id');
        $file = $request->file('image');
        $imgFolder = 'img';
        $imgFile = time()."_".$file->getClientOriginalName();
        $file->move($imgFolder, $imgFile);
        $Medicine = Medicine::find($id);
        $Medicine->image = $imgFile;
        $Medicine->save();
        return redirect('obat')->with('status', 'Medicine image is changed');
    }
}

resources/views/medicine/create.blade.php
@extends('layouts.conquer2')

@section('title')
    Tambah Obat
@endsection

@section('content')
<form method="POST" action="{{route('obat.store')}}" enctype="multipart/form-data" class="form-horizontal">
    @csrf
    <div class="form-body">
        <h3 align='center'>Tambah Obat Baru</h3><br>
        <div class="form-group">
            <label class="col-md-3 control-label">Generic Name</label>
            <div class="col-md-4">
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="fa fa-user"></i>
                    </span>
                    <input id="generic_name" name="generic_name" type="text" class="form-control" placeholder="Generic Name">
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Form</label>
            <div class="col-md-4">
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="fa fa-envelope"></i>
                    </span>
                    <input id="form" name="form" type="text" class="form-control" placeholder="Form">
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Restriction Formula</label>
            <div class="col-md-4">
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="fa fa-envelope"></i>
                    </span>
                    <input id="restriction_formula" name="restriction_formula" type="text" class="form-control" placeholder="Restriction Formula">
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Price</label>
            <div class="col-md-4">
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="fa fa-envelope"></i>
                    </span>
                    <input id="price" name="price" type="number" class="form-control" placeholder="Price">
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Description</label>
            <div class="col-md-4">
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="fa fa-envelope"></i>
                    </span>
                    <input id="description" name="description" type="text" class="form-control" placeholder="Description">
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Category</label>
            <div class="col-md-4">
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="fa fa-envelope"></i>
                    </span>
                    <select id="category_id" name="category_id">
                        @foreach($data as $d)
                            <option value="{{$d->id}}">{{$d->name}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Supplier</label>
            <div class="col-md-4">
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="fa fa-envelope"></i>
                    </span>
                    <select id="supplier_id" name="supplier_id">
                        @foreach($data2 as $d)
                            <option value="{{$d->id}}">{{$d->name}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Faskes 1</label>
            <div class="col-md-4">
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="fa fa-envelope"></i>
                    </span>
                    <input id="faskes1" name="faskes1" type="number" class="form-control" placeholder="Faskes 1">
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Faskes 2</label>
            <div class="col-md-4">
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="fa fa-envelope"></i>
                    </span>
                    <input id="faskes2" name="faskes2" type="number" class="form-control" placeholder="faskes2">
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Faskes 3</label>
            <div class="col-md-4">
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="fa fa-envelope"></i>
                    </span>
                    <input id="faskes3" name="faskes3" type="number" class="form-control" placeholder="Faskes3">
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Image</label>
            <div class="col-md-4">
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="fa fa-image"></i>
                    </span>
                    <input type="file" class="form-control" id="image" name="image" placeholder="image">
                </div>
            </div>
        </div>
    </div>
    <div class="form-actions">
        <div class="row">
            <div class="col-md-offset-3 col-md-9">
                <button type="submit" name="submit" class="btn btn-primary">Submit</button>
                <button type="button" class="btn btn-default">Cancel</button>
            </div>
        </div>
    </div>
</form>
@endsection

resources/views/medicine/index.blade.php
@extends('layouts.conquer2')

@section('title')
    Daftar Obat
@endsection

@section('javascript')
<script>
function showInfo()
{
  $.ajax({
    type:'POST',
    url:'{{route("obat.showInfo")}}',
    data:'_token=<?php echo csrf_token() ?>',
    success: function(data){
       $('#showinfo').html(data.msg)
    }
  });
}
</script>

@section('content')
<div class="page-bar">
  <ul class="page-breadcrumb">
    <li>
      <i class="fa fa-home"></i>
      <a href="index.html">Home</a>
      <i class="fa fa-angle-right"></i>
    </li>
    <li>
      <a href="#" onclick="showInfo()">Welcome
      <i class="icon-bulb"></a></i>
    </li>
  </ul>
</div>
<div id='showinfo'></div>
  @if (session('status'))
      <div class="alert alert-success">
          {{ session('status') }}
      </div>
  @endif

  @if (session('error'))
    <div class="alert alert-danger">
        {{ session('error') }}
    </div>
  @endif

  <h2>List Medicine</h2>

  <div class="page-toolbar">
      <a href="{{ url('obat/create') }}" class='btn btn-info' type="button">+ Obat baru</a>
  </div>          

  <table class="table">
    <thead>
      <tr>
        <th>ID Code</th>
        <th>Name</th>
        <th>Form</th>
        <th>Restriction Formula</th>
        <th>Price</th>
        <th>Description</th>
        <th>Faskes 1</th>
        <th>Faskes 2</th>
        <th>Faskes 3</th>
      </tr>
    </thead>
    <tbody>
        @foreach($listdata as $li)
      <tr>
        <td>
          <a class="btn btn-default" data-toggle="modal" href="#detail_{{$li->id}}">{{ $li->id }}</a>
          <div class="modal fade" id="detail_{{$li->id}}" tabindex="-1" role="basic" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h4 class="modal-title">{{$li-> generic_name}}</h4>
                </div>
                <div class="modal-body">
                  <img src="{{ asset ('img/' .$li -> image) }}" height='200px'>
                  <p>Description:</p>
                  <p>{{ $li -> description }}</p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        </td>
        <td class='editable' id='td_generic_name_{{ $li->id }}'>{{ $li-> generic_name }}</td>
        <td class='editable' id='td_form_{{ $li->id }}'>{{ $li -> form }}</td>
        <td class='editable' id='td_restriction_formula_{{ $li->id }}'>{{ $li -> restriction_formula }}</td>
        <td class='editable' id='td_price_{{ $li->id }}'>{{ $li -> price }}</td>
        <td class='editable' id='td_description_{{ $li->id }}'>{{ $li -> description }}</td>
        <td class='editable' id='td_faskes1_{{ $li->id }}'>{{ $li -> faskes1 }}</td>
        <td class='editable' id='td_faskes2_{{ $li->id }}'>{{ $li -> faskes2 }}</td>
        <td class='editable' id='td_faskes3_{{ $li->id }}'>{{ $li -> faskes3 }}</td>

        <td id='td_image_{{ $li->image }}'>
            <img height="50px" src="{{ asset ('img/' .$li -> image) }}">

        <div class="modal fade" id="modalChange_{{ $li->id }}" tabindex="-1" role="basic" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content" >
                    <form role="form" method='POST' action="{{ route('obat.changeImageMedicine') }}" enctype='multipart/form-data'>
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                            <h4 class="modal-title">Change Image</h4>
                        </div>
                        <div class="modal-body">
                            @csrf 
                            <div class="form-group"> 
                                <label>Image</label> 
                                <input type="file" class="form-control" id='image' name='image'/>
                                <input type='hidden' id='id' name='id' value='{{ $li->id }}'/> 
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-info">Submit</button> 
                            <a data-dismiss="modal" class="btn btn-default">Cancel</a> 
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <br><a href='#modalChange_{{ $li->id }}' data-toggle='modal' class='btn btn-default'>Change</a>
        </td>

        <td>
          <a class='btn btn-info' href="{{route('obat.show',$li->id)}}"
             data-target="#show{{$li->id}}" data-toggle='modal'>Detail</a>        
          <div class="modal fade" id="show{{$li->id}}" tabindex="-1" role="basic" aria-hidden="true">
            <div class="modal-dialog">
             <div class="modal-content">
               <!-- put animated gif here -->
             </div>
            </div>
          </div>
        </td>
        <td><a href="{{ url('obat/'.$li->id.'/edit') }}" class='btn btn-info'>Edit</a></td>
        <td>
          @can ('delete-permission', $li)
          <form method='POST' action="{{ url('obat/'.$li->id) }}">
                @csrf
                @method('DELETE')
                <input type="submit" value="Delete" class="btn btn-danger" onclick="if(!confirm('are you sure to delete this record?')) return false;"/>
          </form>
          @endcan
        </td>
      </tr>
        @endforeach
    </tbody>
  </table>

  <h2>Medicine</h2><br>   
    <div class="row">
        @foreach($listdata as $li)
        <div class="col-12 col-md-3">
            <div class="card mb-6">
                <img src="{{ asset ('img/' .$li -> image)}}" 
                width="300px" height="300px" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">{{ $li -> generic_name }}</h5>
                    <p class="card-text">{{ $li -> form }}</p>
                    <p class="card-text">{{ $li -> price }}</p>
                </div>
            </div>
        </div>
        @endforeach
    </div>
@endsection

@section('initialscript')
<script>
    $('.editable').editable({
        closeOnEnter : true,
        callback:function(data) {
            if(data.content) {
                alert(data.content);

                var s_id = data.$el[0].id;
                var fname = s_id.split('_')[1];
                var id = s_id.split('_')[2];
                
                $.ajax({
                    type:'POST',
                    url:'{{ route("obat.saveDataFieldMedicine") }}',
                    data:{
                        '_token':'<?php echo csrf_token() ?>',
                        'id':id,
                        'fname':fname,
                        'value':data.content
                    },
                    success: function(data) {
                        alert(data.msg)
                    }
                });
            }
        }
    });
</script>
@endsection

resources/views/medicine/obatKategori.blade.php
@extends('layouts.conquer2')

@section('title')
    Obat Satu Kategori
@endsection

@section('content')
<h2>Medicine</h2> 
    <div class="row">
        @foreach($listdata as $li)
        <div class="col-12 col-md-4">
            <div class="card mb-4">
                <img src="{{ asset ('img/' .$li -> image)}}" 
                width="300px" height="300px" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">{{ $li -> generic_name }}</h5>
                    <p class="card-text">{{ $li -> form }}</p>
                    <p class="card-text">{{ $li -> price }}</p>
                </div>
            </div>
        </div>
        @endforeach
    </div>
@endsection

resources/views/medicine/show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Show Medicine</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
    <h2>Show Medicine</h2>
    @if ($msg)
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Form</th>
          <th>Restriction Formula</th>
          <th>Price</th>
          <th>Category</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>{{ $msg -> generic_name }}</td>
          <td>{{ $msg -> form }}</td>
          <td>{{ $msg -> restriction_formula }}</td>
          <td>{{ $msg -> price }}</td>
          <td>{{ ($msg -> category) -> name }}</td>
        </tr>
      </tbody>
    </table>
    @else
    <h3>No Medicine Found</h3>
    @endif
</div>

</body>
</html>