routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('welcome/', function() {
    return view('welcome');
});

Route::get('catalog/', function() {
    return view('menu');
});

Route::get('catalog/medicines', function() {
    return view('product', ['name' => 'medic']);
});

Route::get('catalog/med_equip', function() {
    return view('product', ['name' => 'medic_equip']);
});

Route::get('/medicines/panadol', function () {
    return view('detail', ['id' => 'medic1']);
});

Route::get('/medicines/ultraflu', function () {
    return view('detail', ['id' => 'medic2']);
});

Route::get('/medicines/vitacimin', function () {
    return view('detail', ['id' => 'medic3']);
});

Route::get('/med_equip/stetoskop', function () {
    return view('detail', ['id' => 'med_equip1']);
});

Route::get('/med_equip/masker', function () {
    return view('detail', ['id' => 'med_equip2']);
});

/////////////////////////////////////////////////

Route::get('/helloworld', function (){
    return 'Hello World, Pak Dosen';
});

Route::view('/selamatdatang','welcome');

Route::get('user/{id}', function($id) {
    return 'User '.$id;
});

Route::get('posts/{post}/comments/{comment}', function($postId, $commentId) {
    return 'Post : ' .$postId.'<br>comments : '.$commentId;
});

Route::get('user/{name?}', function($name = 'John') {
    return $name;
});

Route::get('user/profile', function() {
    //
})->name('profile');

Route::get('user/{id}/profile', function($id) {
    //
})->name('profile');

Route::get('wfp/{kelas}', function($kelas){
    if ($kelas == "C" || $kelas == "c") {
        return 'WFP Kelas '.$kelas;
    }
    else {
        return "Bukan Kelas Saya";
    }
});

Route::get('greeting', function() {
    return view('welcome', ['name' => 'Bagus']);
});

Route::get('/', function() {
    return view('welcome');
});

// Week 8
Auth::routes();
Route::get('/', 'MedicineController@front_index');

Route::middleware(['auth'])->group(function() {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('supplier', 'SupplierController');
    Route::resource('obat', 'MedicineController');
    Route::resource('transaksi', 'TransactionController');
    Route::resource('kategori_obat', 'CategoryController');

    Route::post('/supplier/getEditForm', 'SupplierController@getEditForm')->name('supplier.getEditForm');
    Route::post('/supplier/getEditForm2', 'SupplierController@getEditForm2')->name('supplier.getEditForm2');
    Route::post('/supplier/saveData', 'SupplierController@saveData')->name('supplier.saveData');
    Route::post('/supplier/deleteData', 'SupplierController@deleteData')->name('supplier.deleteData');
    Route::post('/supplier/saveDataField', 'SupplierController@saveDataField')->name('supplier.saveDataField');
    Route::post('/supplier/changeLogo', 'SupplierController@changeLogo')->name('supplier.changeLogo');

    Route::get('obatsatukategori', 'MedicineController@tugas')->name('medicines.tugas');
    Route::post('/obat/showInfo','MedicineController@showInfo')->name('obat.showInfo');
    Route::get('cart', 'MedicineController@cart');
    Route::get('add-to-cart/{id}', 'MedicineController@addToCart');
    Route::post('/obat/saveDataFieldMedicine', 'MedicineController@saveDataFieldMedicine')->name('obat.saveDataFieldMedicine');
    Route::post('/obat/changeImageMedicine', 'MedicineController@changeImageMedicine')->name('obat.changeImageMedicine');

    Route::get('transaction', 'TransactionController@Transaction')->name('transaction.transactionlist');
    Route::post('transaction/showDataAjax','TransactionController@showAjax')->name('transaction.showAjax');
    Route::get('/submit_checkout', 'TransactionController@submit_front')->name('submitcheckout');
    Route::get('/checkout', 'TransactionController@form_submit_front');
    Route::get('/cetakpemesanan/{id}', 'TransactionController@print_detail')->name('cetakpesan');

    Route::get('/report/listmedicine/{id}','CategoryController@showlist')->name('reportShowMedicine');
});

app/Supplier.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Supplier extends Model
{
    public function medicines() {
        return $this->hasMany('App\Medicine', 'supplier_id', 'id');
    }

    use SoftDeletes;
}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use App\Supplier;
use Illuminate\Http\Request;

class SupplierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $listdata = Supplier::all();

        return view('supplier.index', compact('listdata'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("supplier.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = new Supplier;

        $file = $request->file('logo');
        $imgFolder = 'img';
        $imgFile = time()."_".$file->getClientOriginalName();
        $file->move($imgFolder, $imgFile);
        $data->logo=$imgFile;

        $data->name = $request->name;
        $data->address = $request->address;
        $data->save();
        return redirect('supplier')->with('status', 'Supplier is added');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function show(Supplier $supplier)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function edit(Supplier $supplier)
    {
        $data = $supplier;
        return view('supplier.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Supplier $supplier)
    {
        $supplier->name=$request->get('name');
        $supplier->address=$request->get('address');
        $supplier->save();
        return redirect()->route('supplier.index')->with('status', 'Supplier data is changed');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function destroy(Supplier $supplier)
    {
        $this->authorize('delete-permission', $supplier);

        try {
            $supplier->delete();
            return redirect()->route('supplier.index')->with('status', 'Data supplier berhasil dihapus');
        } catch (\PDOEXCEPTION $e) {
            $msg = "Data gagal dihapus. Pastikan data child sudah hilang atau tidak berhubungan";

            return redirect()->route('supplier.index')->with('error', $msg);
        }
    }

    public function softDeletes()
    {
        if ($supplier->trashed()) {
            
        }
    }

    public function getEditForm(Request $request)
    {
        $id=$request->get('id');
        $data=Supplier::find($id);
        return response()->json(array(
            'status'=>'oke',
            'msg'=>view('supplier.getEditForm', compact('data'))->render()
        ),200);
    }

    public function getEditForm2(Request $request)
    {
        $id=$request->get('id');
        $data=Supplier::find($id);
        return response()->json(array(
            'status'=>'oke',
            'msg'=>view('supplier.getEditForm2', compact('data'))->render()
        ),200);
    }

    public function saveData(Request $request)
    {
        $id=$request->get('id');
        $Supplier=Supplier::find($id);
        $Supplier->name=$request->get('name');
        $Supplier->address=$request->get('address');
        $Supplier->save();
        return response()->json(array(
            'status'=>'ok',
            'msg'=>'supplier data updated'
        ),200);
    }

    public function deleteData(Request $request)
    {
        try {
            $id=$request->get('id');
            $Supplier=Supplier::find($id);
            $Supplier->delete();
            return response()->json(array(
                'status'=>'ok',
                'msg'=>'supplier data deleted'
            ),200);
        }
        catch(\PDOException $e) {
            return response()->json(array(
                'status'=>'error',
                'msg'=>'supplier is not deleted. It may be used in the product'
            ),200);
        }
    }

    public function saveDataField(Request $request)
    {
        $id = $request->get('id');
        $fname = $request->get('fname');
        $value = $request->get('value');

        $Supplier = Supplier::find($id);
        $Supplier->$fname = $value;
        $Supplier->save();
        return response()->json(array(
            'status'=>'ok',
            'msg'=>'supplier data updated'
        ),200);
    }

    public function changeLogo(Request $request)
    {
        $id = $request->get('id');
        $file = $request->file('logo');
        $imgFolder = 'img';
        $imgFile = time()."_".$file->getClientOriginalName();
        $file->move($imgFolder, $imgFile);
        $Supplier = Supplier::find($id);
        $Supplier->logo = $imgFile;
        $Supplier->save();
        return redirect('supplier')->with('status', 'Supplier logo is changed');
    }
}

resources/views/supplier/create.blade.php
@extends('layouts.conquer2')

@section('title')
    Tambah Supplier
@endsection

@section('content')
<form method="POST" action="{{route('supplier.store')}}" class="form-horizontal" role="form" enctype="multipart/form-data">
    @csrf
    <div class="form-body">
        <h3 align='center'>Tambah Supplier Baru</h3><br>
        <div class="form-group">
            <label class="col-md-3 control-label">Name</label>
            <div class="col-md-4">
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="fa fa-user"></i>
                    </span>
                    <input id="name" name="name" type="text" class="form-control" placeholder="Name">
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Address</label>
            <div class="col-md-4">
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="fa fa-envelope"></i>
                    </span>
                    <input id="address" name="address" type="text" class="form-control" placeholder="Address">
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Logo</label>
            <div class="col-md-4">
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="fa fa-image"></i>
                    </span>
                    <input type="file" class="form-control" id="logo" name="logo" placeholder="Logo">
                </div>
            </div>
        </div>
    </div>
    <div class="form-actions">
        <div class="row">
            <div class="col-md-offset-3 col-md-9">
                <button type="submit" class="btn btn-primary">Submit</button>
                <button type="button" class="btn btn-default">Cancel</button>
            </div>
        </div>
    </div>
</form>
@endsection

resources/views/supplier/edit.blade.php
@extends('layouts.conquer2')

@section('title')
    Edit Supplier
@endsection

@section('content')
<form method="POST" action="{{ url('supplier/'. $data->id) }}" class="form-horizontal">
    @csrf
    @method("PUT")
    <div class="form-body">
        <h3 align='center'>Edit Supplier</h3><br>
        <div class="form-group">
            <label class="col-md-3 control-label">Name</label>
            <div class="col-md-4">
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="fa fa-user"></i>
                    </span>
                    <input id="name" name="name" value="{{ $data->name }}" type="text" class="form-control" placeholder="Name">
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Address</label>
            <div class="col-md-4">
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="fa fa-envelope"></i>
                    </span>
                    <input id="address" name="address" value="{{ $data->address }}" type="text" class="form-control" placeholder="Address">
                </div>
            </div>
        </div>
    </div>
    <div class="form-actions">
        <div class="row">
            <div class="col-md-offset-3 col-md-9">
                <button type="submit" class="btn btn-primary">Submit</button>
                <button type="button" class="btn btn-default">Cancel</button>
            </div>
        </div>
    </div>
</form>
@endsection

resources/views/supplier/getEditForm.blade.php
<form role="form" method='POST' action="{{url('supplier/' .$data->id)}}">
    <div class="modal-header">
        <button type="button" class="close" 
        data-dismiss="modal" aria-hidden="true"></button>
        <h4 class="modal-title">Edit Supplier</h4>
    </div>
    <div class="modal-body">
        @csrf
        @method('PUT')
        <div class="form-body">
            <div class="form-group"> 
                <label >Nama</label> 
                <input type="text" class="form-control" 
                id='name' name='name' value='{{ $data->name }}'> 
            </div>
            <div class="form-group"> 
                <label>Alamat</label> 
                <textarea class="form-control" rows="3" 
                id='address' name='address'
                >{{ $data->address }}</textarea> 
            </div>
        </div>  
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-info">Submit</button> 
        <a href="{{url('supplier')}}" data-dismiss="modal" class="btn btn-default">Cancel</a> 
    </div>
</form>

resources/views/supplier/getEditForm2.blade.php
<form role="form" method='POST' action="{{url('supplier/' .$data->id)}}">
    <div class="modal-header">
        <button type="button" class="close" 
        data-dismiss="modal" aria-hidden="true"></button>
        <h4 class="modal-title">Edit Supplier</h4>
    </div>
    <div class="modal-body">
        @csrf
        @method('PUT')
        <div class="form-body">
            <div class="form-group"> 
                <label >Nama</label> 
                <input type="text" class="form-control" 
                id='eName' name='name' value='{{ $data->name }}'> 
            </div>
            <div class="form-group"> 
                <label>Alamat</label> 
                <textarea class="form-control" rows="3" 
                id='eAddress' name='address'
                >{{ $data->address }}</textarea> 
            </div>
        </div>  
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal" onclick="saveDataUpdateTD({{ $data->id }})">Submit</button> 
        <a href="{{url('supplier')}}" data-dismiss="modal" class="btn btn-default">Cancel</a> 
    </div>
</form>

resources/views/supplier/index.blade.php
@extends('layouts.conquer2')

@section('title')
  Daftar Suppliers
@endsection

@section('javascript')
<script>
function getDetailData(id) 
{
    $.ajax({
        type:'POST',
        url:'{{route("transaction.showAjax")}}',
        data:'_token=<?php echo csrf_token() ?> &id=' + id,
        success: function(data){
        $("#msg").html(data.msg);
        }
    });
}

function getEditForm(id) 
{
    $.ajax({
        type:'POST',
        url:'{{route("supplier.getEditForm")}}',
        data:{'_token':'<?php echo csrf_token() ?>',
            'id':id
            },
        success: function(data){
        $("#modalContent").html(data.msg);
        }
    });
}

function getEditForm2(id) 
{
    $.ajax({
        type:'POST',
        url:'{{route("supplier.getEditForm2")}}',
        data:{'_token':'<?php echo csrf_token() ?>',
            'id':id
            },
        success: function(data){
        $("#modalContent").html(data.msg);
        }
    });
}

function saveDataUpdateTD(id) 
{
    var eName=$('#eName').val();
    var eAddress=$('#eAddress').val();
    $.ajax({
        type:'POST',
        url:'{{route("supplier.saveData")}}',
        data:{'_token':'<?php echo csrf_token() ?>',
            'id':id,
            'name':eName,
            'address':eAddress
            },
        success: function(data){
            if(data.status == "ok")
            {
                alert(data.msg)
                $('#td_name' + id).html(eName);
                $('#td_address' + id).html(eAddress);
            }
        }
    });
}

function deleteDataRemoveTR(id) 
{
    $.ajax({
        type:'POST',
        url:'{{route("supplier.deleteData")}}',
        data:{'_token':'<?php echo csrf_token() ?>',
            'id':id
            },
        success: function(data){
            if(data.status == "ok")
            {
                alert(data.msg)
                $('#tr_' + id).remove();
            }
            else 
            {
                alert(data.msg)
            }
        }
    });
}
</script>
@endsection

@section('content')
@if (session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
@endif

@if (session('error'))
    <div class="alert alert-danger">
        {{ session('error') }}
    </div>
@endif

<div class="modal fade" id="modalCreate" tabindex="-1" role="basic" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" >
            <form role="form" method='POST' action="{{url('supplier')}}">
                <div class="modal-header">
                    <button type="button" class="close" 
                    data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title">Add New Supplier</h4>
                </div>
                <div class="modal-body">
                        @csrf 
                        <div class="form-body">
                            <div class="form-group"> 
                                <label >Nama</label> 
                                <input type="text" class="form-control" 
                                id='name' name='name'> 
                            </div>
                            <div class="form-group"> 
                                <label>Alamat</label> 
                                <textarea class="form-control" rows="3" 
                                id='address' name='address'
                                ></textarea> 
                            </div>
                        </div>  
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-info">Submit</button> 
                    <a href="{{url('supplier')}}" data-dismiss="modal" class="btn btn-default">Cancel</a> 
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="modalEdit" tabindex="-1" role="basic" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" id="modalContent"></div>
    </div>
</div>

<div class="page-toolbar">
    <a href="{{ url('supplier/create') }}" class='btn btn-info' type="button">+ Supplier baru</a>
    <a href="#modalCreate" data-toggle='modal' class='btn btn-info'>+ Supplier baru (modal)</a>
</div><br>

<table class='table'>
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Address</th>
            <th>Logo</th>
        </tr>
    </thead>
    <tbody>
    @foreach($listdata as $d)
    <tr id='tr_{{ $d->id }}'>
        <td>{{ $d->id }}</td>
        <td class="editable" id='td_name_{{ $d->id }}'>{{ $d->name }}</td>
        <td class="editable" id='td_address_{{ $d->id }}'>{{ $d->address }}</td>
        <td id='td_logo_{{ $d->logo }}'>
            <img height="50px" src="{{ asset ('img/' .$d -> logo) }}">

        <div class="modal fade" id="modalChange_{{ $d->id }}" tabindex="-1" role="basic" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content" >
                    <form role="form" method='POST' action="{{ route('supplier.changeLogo') }}" enctype='multipart/form-data'>
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                            <h4 class="modal-title">Change Logo</h4>
                        </div>
                        <div class="modal-body">
                            @csrf 
                            <div class="form-group"> 
                                <label>Logo</label> 
                                <input type="file" class="form-control" id='logo' name='logo'/>
                                <input type='hidden' id='id' name='id' value='{{ $d->id }}'/> 
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-info">Submit</button> 
                            <a data-dismiss="modal" class="btn btn-default">Cancel</a> 
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <br><a href='#modalChange_{{ $d->id }}' data-toggle='modal' class='btn btn-default'>Change</a>
        </td>

        <td>
            <a href="{{ url('supplier/'.$d->id.'/edit') }}" class='btn btn-xs btn-info'>Edit</a>
            <a href="#modalEdit" data-toggle='modal' class='btn btn-warning btn-xs' onclick="getEditForm({{ $d->id }})">+ Edit A</a>
            <a href="#modalEdit" data-toggle='modal' class='btn btn-warning btn-xs' onclick="getEditForm2({{ $d->id }})">+ Edit B</a>
        </td>
        <td>
        @can ('delete-permission', $d)
            <form method='POST' action="{{ url('supplier/'.$d->id) }}">
                @csrf
                @method('DELETE')
                <input type="submit" value="Delete" class="btn btn-danger btn-xs" onclick="if(!confirm('Are you sure to delete this record?')) return false;"/>
                <a class='btn btn-danger btn-xs' onclick="if(confirm('Are you sure to delete this record?'))
                deleteDataRemoveTR({{ $d->id }})">Delete 2 </a>
            </form>
        @endcan
        </td>
    </tr>
    @endforeach
    </tbody>
</table>
@endsection

@section('initialscript')
<script>
    $('.editable').editable({
        closeOnEnter : true,
        callback:function(data) {
            if(data.content) {
                alert(data.content);

                var s_id = data.$el[0].id;
                var fname = s_id.split('_')[1];
                var id = s_id.split('_')[2];
                
                $.ajax({
                    type:'POST',
                    url:'{{ route("supplier.saveDataField") }}',
                    data:{
                        '_token':'<?php echo csrf_token() ?>',
                        'id':id,
                        'fname':fname,
                        'value':data.content
                    },
                    success: function(data) {
                        alert(data.msg)
                    }
                });
            }
        }
    });
</script>
@endsection